// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETuNUBFboBSBFyCY0Lsc9BDFGFR5lSGc',
    appId: '1:500842626317:android:757806e07e16e78ba68444',
    messagingSenderId: '500842626317',
    projectId: 'deliverzler-46479',
    storageBucket: 'deliverzler-46479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFygdpaXJl4D7cOJ7QWp9hnouh4sjKipo',
    appId: '1:500842626317:ios:1ef89d78ac93ceaea68444',
    messagingSenderId: '500842626317',
    projectId: 'deliverzler-46479',
    storageBucket: 'deliverzler-46479.appspot.com',
    androidClientId: '500842626317-mbfoobmju60ond4eeq0rmm0r4vqaclfl.apps.googleusercontent.com',
    iosClientId: '500842626317-o936te8vfulj3qpdke0n6esrjcu97l3e.apps.googleusercontent.com',
    iosBundleId: 'dev.bhato.shipper',
  );
}
